"""evaluatee->evaluated

Revision ID: 086a81bed888
Revises: e7e764a7f2a2
Create Date: 2025-12-30 20:58:31.742682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '086a81bed888'
down_revision: Union[str, Sequence[str], None] = 'e7e764a7f2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_users', sa.Column('evaluated_total_evals', sa.Integer(), nullable=True))
    op.add_column('processed_users', sa.Column('evaluated_avg_time', sa.Integer(), nullable=True))
    op.add_column('processed_users', sa.Column('evaluated_avg_grade', sa.Float(), nullable=True))
    op.add_column('processed_users', sa.Column('evaluated_epp', sa.Integer(), nullable=True))
    op.add_column('processed_users', sa.Column('evaluated_top', sa.JSON(), nullable=True))
    op.drop_column('processed_users', 'evaluatee_top')
    op.drop_column('processed_users', 'evaluatee_avg_grade')
    op.drop_column('processed_users', 'evaluatee_total_evals')
    op.drop_column('processed_users', 'evaluatee_avg_time')
    op.drop_column('processed_users', 'evaluatee_epp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_users', sa.Column('evaluatee_epp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processed_users', sa.Column('evaluatee_avg_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processed_users', sa.Column('evaluatee_total_evals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processed_users', sa.Column('evaluatee_avg_grade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('processed_users', sa.Column('evaluatee_top', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('processed_users', 'evaluated_top')
    op.drop_column('processed_users', 'evaluated_epp')
    op.drop_column('processed_users', 'evaluated_avg_grade')
    op.drop_column('processed_users', 'evaluated_avg_time')
    op.drop_column('processed_users', 'evaluated_total_evals')
    # ### end Alembic commands ###
