"""reworked defaults in processed_user

Revision ID: a5ea2fbdf19b
Revises: b845ce79cf36
Create Date: 2025-12-29 14:30:11.456114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ea2fbdf19b'
down_revision: Union[str, Sequence[str], None] = 'b845ce79cf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_users', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_users', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
