"""create processed_users table

Revision ID: a84bf3dd88c8
Revises: 79d46faf40c7
Create Date: 2025-12-28 20:54:35.752863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84bf3dd88c8'
down_revision: Union[str, Sequence[str], None] = '79d46faf40c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_logtime', sa.JSON(), nullable=False),
    sa.Column('raw_evals', sa.JSON(), nullable=False),
    sa.Column('evaluator_total_evals', sa.Integer(), nullable=True),
    sa.Column('evaluator_avg_time', sa.Integer(), nullable=True),
    sa.Column('evaluator_avg_grade', sa.Float(), nullable=True),
    sa.Column('evaluator_invalid_evals', sa.Integer(), nullable=True),
    sa.Column('evaluator_top', sa.JSON(), nullable=True),
    sa.Column('evaluatee_total_evals', sa.Integer(), nullable=True),
    sa.Column('evaluatee_avg_time', sa.Integer(), nullable=True),
    sa.Column('evaluatee_avg_grade', sa.Float(), nullable=True),
    sa.Column('evaluatee_epp', sa.Integer(), nullable=True),
    sa.Column('evaluatee_top', sa.JSON(), nullable=True),
    sa.Column('outercore', sa.Boolean(), nullable=True),
    sa.Column('night_stud', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evals_not_at_school', sa.Integer(), nullable=True),
    sa.Column('processed_logtime', sa.JSON(), nullable=True),
    sa.Column('processed_evals', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ft_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_users')
    # ### end Alembic commands ###
